### PR TITLE
Redmine 5.0.0 support

### LINKED ISSUE #36: Redmine 5.0.0 support
Thanks for the great plugin!

Are there any plans for supporting Redmine >= 5.0.0?
There has been a large amount of changes, first of all the use of Rails 6.1 with Zeitwerk autoloader.
https://www.redmine.org/news/135

### PR DESCRIPTION
**Pull request by friedz**
fixes #36

### CODE REVIEW

**Comment by friedz** [comment]
i have only just now seen that there already is PR #37 for this

**Comment by tf** [comment]
Thanks for the PR. I think this approach reads a bit better than what has been proposed in #37. Could you also add Redmine 5 to the [test matix](https://github.com/tf/redmine_merge_request_links/blob/e04a606d6dda1420486c8c5b81990f777cc9433f/.github/workflows/tests.yml#L11) to make sure everything integrates correctly?

**Comment by friedz** [comment]
maybe i also should have commented that i've done it, but Redmine 5 is added to the test matrix

**Comment by tf** [comment]
Thanks for the heads-up!

**Pull request merged**
